CREATE TABLE [rally] (
   [externalIdRally] INTEGER,
   [externalIdEvent] INTEGER,
   [itineraryId] INTEGER,
   [name] TEXT,
   [isMain] INTEGER,
   [eventClasses] TEXT,
   [sdbRallyId] INTEGER
)CREATE TABLE [eligibilities] (
   [category] TEXT,
   [externalIdRally] INTEGER,
   [sdbRallyId] INTEGER,
   PRIMARY KEY ([sdbRallyId], [category])
)CREATE TABLE [groups] (
   [groupId] INTEGER,
   [name] TEXT,
   [externalIdRally] INTEGER,
   [sdbRallyId] INTEGER,
   PRIMARY KEY ([sdbRallyId], [groupId])
)CREATE TABLE [itinerary] (
   [itineraryId] INTEGER,
   [eventId] INTEGER,
   [name] TEXT,
   [priority] INTEGER,
   [rallyid] INTEGER
)CREATE TABLE [legs] (
   [itineraryLegId] INTEGER,
   [itineraryId] INTEGER,
   [startListId] FLOAT,
   [name] TEXT,
   [legDate] TEXT,
   [order] INTEGER,
   [status] TEXT,
   [rallyid] INTEGER
)CREATE TABLE [sections] (
   [itinerarySectionId] INTEGER,
   [itineraryLegId] INTEGER,
   [order] INTEGER,
   [name] TEXT,
   [rallyid] INTEGER
)CREATE TABLE [controls] (
   [controlId] INTEGER,
   [eventId] INTEGER,
   [stageId] FLOAT,
   [type] TEXT,
   [code] TEXT,
   [location] TEXT,
   [timingPrecision] TEXT,
   [distance] FLOAT,
   [targetDuration] TEXT,
   [targetDurationMs] FLOAT,
   [firstCarDueDateTime] TEXT,
   [firstCarDueDateTimeLocal] TEXT,
   [status] TEXT,
   [controlPenalties] TEXT,
   [roundingPolicy] TEXT,
   [locked] INTEGER,
   [itineraryLegId] INTEGER,
   [startListId] INTEGER,
   [rallyid] INTEGER
)CREATE TABLE [stages] (
   [stageId] INTEGER,
   [eventId] INTEGER,
   [number] INTEGER,
   [name] TEXT,
   [distance] FLOAT,
   [status] TEXT,
   [stageType] TEXT,
   [timingPrecision] TEXT,
   [locked] INTEGER,
   [code] TEXT,
   [itineraryLegId] INTEGER,
   [startListId] INTEGER,
   [rallyid] INTEGER
)CREATE TABLE [richstages] (
   [stageId] INTEGER,
   [eventId] INTEGER,
   [number] INTEGER,
   [name] TEXT,
   [distance] FLOAT,
   [status] TEXT,
   [stageType] TEXT,
   [timingPrecision] TEXT,
   [locked] INTEGER,
   [code] TEXT,
   [itineraryLegId] INTEGER,
   [startListId] INTEGER,
   [rallyid] INTEGER,
   [controlPenalties] TEXT,
   [firstCarDueDateTime] TEXT,
   [location] TEXT,
   [targetDurationMs] FLOAT,
   [firstCarDueDateTimeLocal] TEXT,
   [roundingPolicy] TEXT,
   [type] TEXT,
   [targetDuration] TEXT,
   [controlId] INTEGER
)CREATE TABLE [penalties] (
   [penaltyId] INTEGER PRIMARY KEY,
   [controlId] INTEGER,
   [entryId] INTEGER,
   [penaltyDurationMs] INTEGER,
   [penaltyDuration] TEXT,
   [reason] TEXT
)CREATE TABLE [retirements] (
   [retirementId] INTEGER PRIMARY KEY,
   [controlId] INTEGER,
   [entryId] INTEGER,
   [reason] TEXT,
   [retirementDateTime] TEXT,
   [retirementDateTimeLocal] TEXT,
   [status] TEXT
)CREATE TABLE [stagewinners] (
   [stageId] INTEGER,
   [entryId] FLOAT,
   [stageName] TEXT,
   [elapsedDurationMs] FLOAT,
   [elapsedDuration] TEXT,
   PRIMARY KEY ([stageId], [entryId])
)CREATE TABLE [cars] (
   [tag] TEXT,
   [entryId] INTEGER,
   [eventId] INTEGER,
   [driverId] INTEGER,
   [codriverId] INTEGER,
   [manufacturerId] INTEGER,
   [entrantId] INTEGER,
   [groupId] INTEGER,
   [tagId] TEXT,
   [entryListOrder] INTEGER,
   [identifier] TEXT,
   [vehicleModel] TEXT,
   [eligibility] TEXT,
   [priority] TEXT,
   [status] TEXT,
   [tyreManufacturer] TEXT,
   [driver.personId] INTEGER,
   [driver.countryId] INTEGER,
   [driver.country.countryId] INTEGER,
   [driver.country.name] TEXT,
   [driver.country.iso2] TEXT,
   [driver.country.iso3] TEXT,
   [driver.firstName] TEXT,
   [driver.lastName] TEXT,
   [driver.abbvName] TEXT,
   [driver.fullName] TEXT,
   [driver.code] TEXT,
   [codriver.personId] INTEGER,
   [codriver.countryId] INTEGER,
   [codriver.country.countryId] INTEGER,
   [codriver.country.name] TEXT,
   [codriver.country.iso2] TEXT,
   [codriver.country.iso3] TEXT,
   [codriver.firstName] TEXT,
   [codriver.lastName] TEXT,
   [codriver.abbvName] TEXT,
   [codriver.fullName] TEXT,
   [codriver.code] TEXT,
   [manufacturer.manufacturerId] INTEGER,
   [manufacturer.name] TEXT,
   [manufacturer.logoFilename] TEXT,
   [entrant.entrantId] INTEGER,
   [entrant.name] TEXT,
   [entrant.logoFilename] TEXT,
   [group.groupId] INTEGER,
   [group.name] TEXT,
   PRIMARY KEY ([entryId], [eventId])
)CREATE TABLE [classes] (
   [eventClassId] INTEGER,
   [eventId] INTEGER,
   [name] TEXT,
   [entryId] INTEGER
)CREATE TABLE [overall] (
   [entryId] INTEGER,
   [stageTimeMs] INTEGER,
   [stageTime] TEXT,
   [penaltyTimeMs] INTEGER,
   [penaltyTime] TEXT,
   [totalTimeMs] INTEGER,
   [totalTime] TEXT,
   [position] INTEGER,
   [diffFirstMs] INTEGER,
   [diffFirst] TEXT,
   [diffPrevMs] INTEGER,
   [diffPrev] TEXT,
   [stageId] INTEGER,
   PRIMARY KEY ([stageId], [entryId])
)CREATE TABLE [stagetimes] (
   [stageTimeId] INTEGER,
   [stageId] INTEGER,
   [entryId] INTEGER,
   [elapsedDurationMs] FLOAT,
   [elapsedDuration] TEXT,
   [status] TEXT,
   [source] TEXT,
   [position] FLOAT,
   [diffFirstMs] FLOAT,
   [diffFirst] TEXT,
   [diffPrevMs] FLOAT,
   [diffPrev] TEXT,
   PRIMARY KEY ([stageId], [entryId])
)CREATE TABLE [splitPoints] (
   [splitPointId] INTEGER,
   [stageId] INTEGER,
   [number] INTEGER,
   [distance] FLOAT,
   PRIMARY KEY ([splitPointId], [stageId])
)CREATE TABLE [entrySplitPointTimes] (
   [entryId] INTEGER,
   [startDateTime] TEXT,
   [startDateTimeLocal] TEXT,
   [stageTimeDurationMs] FLOAT,
   [stageTimeDuration] TEXT,
   [stageId] INTEGER,
   PRIMARY KEY ([stageId], [entryId])
)CREATE TABLE [splitPointTimes] (
   [splitPointTimeId] INTEGER,
   [splitPointId] INTEGER,
   [entryId] INTEGER,
   [elapsedDurationMs] INTEGER,
   [elapsedDuration] TEXT,
   [splitDateTime] TEXT,
   [splitDateTimeLocal] TEXT,
   [stageId] INTEGER,
   PRIMARY KEY ([splitPointTimeId], [splitPointId], [entryId], [stageId])
)